# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'S.H.I.E.L.D. Hero Tracker' do
pod 'Parse'
end


